### ISSUE TITLE
Will not compile on the ESP Huzzah

### ISSUE THREAD

**Issue by skandragon** [adafruit/Adafruit_Sensor#8]
This is likely because it requires avr/pgmspace.h, which won't exist on a non-AVR.

I am wanting to get the BNO055 to be read on this device, so I may tinker a bit.

**Comment by tdicola** [comment]
Ah thanks for pointing it out.  Looks like it's not really used in this library so I pulled out the reference and commited the change.

Also for the BNO-055 on the ESP8266 I tried to get it to work too but was running into some trouble getting it to respond.  I ran out of time to mess with it but just an FYI there might be some trickiness with the ESP8266's I2C support and the BNO-055.  I'm not sure if they're still using a software GPIO I2C implementation that might be causing issues.  Either way good luck and let us know if you can get the BNO-055 working on it, thanks!

**Comment by skandragon** [comment]
There are other issues, like Wire.begin() being used, where on the ESP8266 we need to do a Wire.begin(int sda, int sdc) sort of call to set the pins.  I'll see if this can be worked around; perhaps there is a way to say "I'll initialize Wire for you, please don't do this for me" or modify the ESP's Wire implementation to allow for calling Wire.begin() without arguments after Wire.begin(int,int).  That path is probably better, but this may not fix chips which do actually have multiple i2c hardware interfaces.  Generally, it may be better to have Wire passed in as an argument to the constructor, rather than initializing it for me.  This is typical for dependency injection.

**Comment by tdicola** [comment]
Yeah actually I think in the latest ESP8266 code if you don't call wire.begin() with the SDA and SDC params it will default to SDA=4 and SCL=5.  It seemed to work ok when I was trying it with some other I2C devices that weren't calling begin with explicit pins.

I actually dug in a little more to my ESP8266 + BNO-055 issue and realized the bigger problem we're going to run into is that the BNO-055 uses I2C clock stretching (in the datasheet it mentions in section 4.6 "The BNO055 I²C interface uses clock stretching.").  This is probably why I couldn't seem to get any response from the BNO-055 when I tried to use it earlier, I'm guessing the ESP8266 doesn't support clock stretching, at least with the current ESP8266 Arduino code.  Just an FYI in case you hit the same brick wall that the BNO doesn't seem to respond, you might want to dig around and check the ESP8266 forums to see if there's an API to call or other way to enable I2C clock stretching.

**Comment by skandragon** [comment]
I'm new to i2c (although I understand how it works pretty well, having used similar protocols before i2c was around) -- the clock stretching part did concern me.  I do see activity on pin 4 and 5, but my logic analyzer is 1,500 miles from me at the moment.

In core_sxp8266_si2c.c (which is bit-banging code) I do see some type of support for clock stretching, of up to 100uS.  I did find this issue:  https://github.com/esp8266/Arduino/issues/254 which seems related.  I also opened this issue up on https://github.com/esp8266/Arduino/issues/526, rather than continue discussing it here.  :)

**Comment by igrr** [comment]
@tdicola we do have support for clock stretching in the core:
https://github.com/esp8266/Arduino/blob/esp8266/hardware/esp8266com/esp8266/cores/esp8266/core_esp8266_si2c.c#L113
although i don't have any devices which actually stretch clock to do a test.
If you find wrong behaviour, please send me scope pics and i'll take a look.

**Comment by skandragon** [comment]
@tdicola I managed to get some (still limited) success.  I am getting good data, but occasionally I get totally insane data, and occasionally it falls out of sync in some fatal way.

See esp8266/Arduino#526 for some details.  it does seem to be related to clock stretching -- but i'm not sure if the BNO055 is insane, or if the ESP8266 is yet.  Something is causing the clock to be stretched over 150uS, seemingly at random.

**Comment by tdicola** [comment]
Oh interesting, that's awesome you could get some results.  I've actually been trying to get it to work with the Raspberry Pi and ran into similar random glitches.  Unfortunately the Pi has a hardware issue with I2C clock stretching so it's not easy to fix (although one workaround was to run the Pi's I2C bus at 10khz instead of 100khz, but even then I still saw some random glitchy values).  

As a workaround though I've been implementing the BNO-055's UART protocol and have had good success with it.  Can see more details in section 4.7 of the datasheet (http://www.adafruit.com/datasheets/BST_BNO055_DS000_12.pdf) but the basic idea is to pull PS1 up to 3.3V (and keep PS0 down at ground, it has a pull-down resistor to ground on it on the board) and the BNO-055 will use the SCL and SDA pins as UART TX and RX at 115200 baud.  There's a small bit of framing that you add to register read and write requests and then it operates mostly like accessing the chip over I2C.

If all else fails I think we could probably add UART support to the BNO-055 Arduino library.  I'll move this discussion over to a new bug on the BNO-055 library though so it's easier to find there.
